### ISSUE TITLE
switch off reboot process, because DEP

### ISSUE THREAD

**Issue by salihzett** [ox-it/munki-rebrand#22]
after an Installation over imagr (f.e.) the mac reboots. my custom munki with munki-reband is the reason. in your old Version, it was possible to deactivated. the argument -d is missing now.

**Comment by fuzzylogiq** [comment]
That's because it no longer builds munki, which is what used to happen. To do what you want, you will need to run the [make_munki_mpkg_DEP.sh](https://github.com/munki/munki/blob/master/code/tools/make_munki_mpkg_DEP.sh) script with Xcode installed as before, then point munki_rebrand at your resultant pkg. It's down to you to chain these two together now - you could write a wrapper. But I don't want a dependency on Xcode for munki_rebrand.
