### ISSUE TITLE
Pre-requisites version mismatch

### ISSUE THREAD

**Issue by Steffan-Ravn** [ox-it/munki-rebrand#37]
Under Munki-rebrands Pre-requisites, the following is stated:
- Apple Mac running OS X/macOS 10.12+
- Xcode 10+ (opened once, components installed)

But as far as I can tell Xcode 10+ will only run on macOS 10.13.6 or later, according to this release note from Apple:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

Shouldn't the Pre-requisites then list macOS 10.13.6 as the minimum?
Is it possible to run the latest Munki-Rebrand on macOS 10.12?
Is Xcode 10 _required_?

**Comment by lifeunexpected** [comment]
Munki Rebrand works on macOS Mojave and i think macOS Catalina.
Xcode 10 works and i think xcode 11 but not sure becuase i cant remember if i ran it last time on xcode 10 or 11

**Comment by fuzzylogiq** [comment]
XCode 10 is required to rebrand any version of munki since it moved to a swift codebase, since the way it rebrands the icon has by necessity had to change to use a tool only available with Xcode.

You can still rebrand earlier versions with 10.12 and without Xcode...but i should probably get around to updating these as who really wants to do that these days.

**Comment by Steffan-Ravn** [comment]
Thanks for clearing that up - I found out the hard way. 😉
It actually builds withour error on 10.12 and with Xcode 9, but the rebranded icon is missing on newer versions of macOS. 🙄
